language: c++
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
  
script:
  - sudo apt-get install assimp-utils libasound2-dev libx11-dev libwayland-client0 libwayland-dev libassimp-dev -y
  - mv TEST_CMakeLists.txt CMakeLists.txt
  - cd tests
  - cmake ..
  - make
  - chmod +x ci_test
  - ./ci_test
  - cd ../
  - cat RefCMakeLists.txt > CMakeLists.txt
  - mkdir Make
  - cd Make
  - cmake ..
  - make