language: c++
sudo: required
dist: xenial

os:
    - linux

compiler:
    - clang

before_install:  
  - sudo apt-get update -qq


install:
  - sudo apt-get install clang libasound2-dev libx11-dev libwayland-client0 libwayland-dev libxkbcommon-dev libdbus-1-dev wayland-protocols
  - export CXX="clang++"

  
script:
  - cat RefCMakeLists.txt > CMakeLists.txt
  - mkdir Make
  - cd Make
  - cmake -DBUILD_STEP=OFF ..
  - make
  - cd ../
  - cat TEST_CMakeLists.txt > CMakeLists.txt
  - cd tests
  - cmake ..
  - make
  - chmod +x ci_test
  - ./ci_test
  - cd ../
