version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug

before_build:
   - curl https://drive.google.com/open?id=1V7ootcrlyJ8TpX_freUOeqpIYxWkirhP --output cu_additional.zip
   - 7z e cu_additional.zip
   - cd cu_additional
   - move rsrc ..
   - move extlib ..
   - cd ..
   - type RefCMakeLists.txt > CMakeLists.txt
   - mkdir Make
   - cd Make
   - cmake -G "Visual Studio 15 2017 Win64" ..

build:
   project: Make\ALL_BUILD.vcxproj