version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug

install:

before_build:
   - curl -L https://downloads.sourceforge.net/project/assimp/assimp-3.1/assimp-3.1.1-win-binaries.zip > assimp.zip
   - 7z e assimp.zip -n
   - mkdir extlib
   - cd assimp\assimp-3.1.1-win-binaries\lib64\
   - move assimp.lib ..\..\..\extlib\
   - cd ..\..\..\
   - type RefCMakeLists.txt > CMakeLists.txt
   - mkdir Make
   - cd Make
   - cmake -G "Visual Studio 15 2017 Win64" ..

build:
   project: Make\ALL_BUILD.vcxproj