version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug

before_build:
   - type RefCMakeLists.txt > CMakeLists.txt
   - mkdir Make
   - ps: cd Make
   - cmake -G "Visual Studio 15 2017 Win64" ..

build:
   project: ALL_BUILD.vcxproj