version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

before_build:
   - mkdir Make
   - cd Make
   - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: ALL_BUILD.vcxproj