version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug

install:

before_build:
   - curl -L https://edrickhong.github.io/Pages/cu_additional.zip > cu_additional.zip
   - 7z x cu_additional.zip
   - type RefCMakeLists.txt > CMakeLists.txt
   - mkdir Make
   - cd Make
   - cmake -DBUILD_STEP=OFF -G "Visual Studio 15 2017 Win64" ..

build:
   project: Make\ALL_BUILD.vcxproj