version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug

install:
  - choco install wget -y -f --allow-empty-checksums

before_build:
   - wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1V7ootcrlyJ8TpX_freUOeqpIYxWkirhP'
   - 7z e cu_additional.zip
   - cd cu_additional
   - move rsrc ..
   - move extlib ..
   - cd ..
   - type RefCMakeLists.txt > CMakeLists.txt
   - mkdir Make
   - cd Make
   - cmake -G "Visual Studio 15 2017 Win64" ..

build:
   project: Make\ALL_BUILD.vcxproj