#ifdef PREPROCESS

#define INSTRATE INSTRATE
#define DYNBUFFER DYNBUFFER
#define MATERIAL_DIFFUSE MATERIAL_DIFFUSE
#define MATERIAL_SPECULAR MATERIAL_DIFFUSE
#define MATERIAL_NORMAL MATERIAL_NORMAL
#define DEF_MATERIAL DEF_MATERIAL

#else

#define INSTRATE
#define DYNBUFFER
#define MATERIAL_DIFFUSE
#define MATERIAL_SPECULAR
#define MATERIAL_NORMAL
#define DEF_MATERIAL

#endif

#define _disable_vt 0
