/*This file is generated by the preprocessor*/ 
#include"pparse.h"

struct MetaDataEntry{
u32 type_hash;
u32 name_hash;
const s8* type_string;
const s8* name_string;
u32 size;
u32 offset;
};


_persist MetaDataEntry Character_META[] = {
{(u32)3568162,(u32)113380020,"s8*","name",sizeof(s8*),offsetof(Character,name)},
{(u32)3751062,(u32)-1189783696,"u32","health",sizeof(u32),offsetof(Character,health)},
{(u32)3751062,(u32)2966111,"u32","atk",sizeof(u32),offsetof(Character,atk)},
};

_persist MetaDataEntry BossCharacter_META[] = {
{(u32)37259070,(u32)37259070,"Character","character",sizeof(Character),offsetof(BossCharacter,character)},
{(u32)3568162,(u32)-1645698039,"s8*","character::name",sizeof(s8*),offsetof(Character,name) + offsetof(BossCharacter,character)},
{(u32)3751062,(u32)172613528,"u32","character::health",sizeof(u32),offsetof(Character,health) + offsetof(BossCharacter,character)},
{(u32)3751062,(u32)874752742,"u32","character::atk",sizeof(u32),offsetof(Character,atk) + offsetof(BossCharacter,character)},
{(u32)3751062,(u32)-1511689495,"u32","special_ability",sizeof(u32),offsetof(BossCharacter,special_ability)},
};

u32 MetaGetTypeByName(void* indata,const s8* name,const MetaDataEntry* array,
u32 array_count){

MetaDataEntry entry = {};
u32 found = 0;
u32 hash = PHashString(name);
for(u32 i = 0; i < array_count; i++){
entry = array[i];
if(entry.name_hash == hash){
found = true;
break;  
}
}
_kill("entry not found",!found);
return entry.type_hash;
}


void MetaGetValueByName(void* indata,void* outdata,const s8* name,
const MetaDataEntry* array,u32 array_count){

MetaDataEntry entry = {};
u32 found = 0;
u32 hash = PHashString(name);
for(u32 i = 0; i < array_count; i++){
entry = array[i];
if(entry.name_hash == hash){
found = true;
break;  
}
}
  _kill("entry not found",!found);
auto data = (s8*)indata;
memcpy(outdata,data + entry.offset,entry.size);
}
